services:
  - type: web
    name: interview-assist-backend
    env: python
    pythonVersion: "3.10.11"
    rootDir: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    plan: free